[package]
name = "kube-anypod"
version = "0.3.0"
edition = "2024"
authors = ["Frank Wiles <frank@revsys.com>"]
description = "Command line utility to quickly get the name of a random pod from a Deployment, StatefulSet or DaemonSet"
license = "BSD-3-Clause"
homepage = "https://github.com/frankwiles/kube-anypod"
keywords = ["kubernetes", "k8s", "kube"]
categories = ["command-line-utilities"]
exclude = [
  ".github/",
]

[lib]
name = "anypod"
path = "src/lib.rs"

[[bin]]
name = "anypod"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
async-trait = "0.1.89"
clap = { version = "4.5.54", features = ["derive"] }
colorful = "0.3.2"
k8s-openapi = { version = "0.27.0", default-features = false, features = ["v1_32"] }
kube = "3.0.0"
kube-runtime = "3.0.0"
tokio = { version = "1.49.0", features = ["full"] }

