name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test

  release:
    needs: test
    name: Release - ${{ matrix.platform.release_for }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            binary_path: target/release/anypod
            asset_name: anypod-linux-x86_64
            
          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_path: target/release/anypod.exe
            asset_name: anypod-windows-x86_64.exe
            
          - release_for: macOS-x86_64
            os: macos-latest
            target: x86_64-apple-darwin
            binary_path: target/release/anypod
            asset_name: anypod-macos-x86_64
            
          - release_for: macOS-aarch64
            os: macos-latest
            target: aarch64-apple-darwin
            binary_path: target/release/anypod
            asset_name: anypod-macos-aarch64

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
          override: true
      
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.platform.target }}

      - name: Generate SHA256 checksums
        run: |
          if [ "${{ matrix.platform.os }}" = "windows-latest" ]; then
            certutil -hashfile ${{ matrix.platform.binary_path }} SHA256 > ${{ matrix.platform.asset_name }}.sha256
          else
            shasum -a 256 ${{ matrix.platform.binary_path }} > ${{ matrix.platform.asset_name }}.sha256
          fi

      - name: Generate Release Notes
        if: matrix.platform.os == 'ubuntu-latest'
        id: changelog
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          output: CHANGELOG.md

      - name: Set Release Body
        if: matrix.platform.os == 'ubuntu-latest'
        run: |
          body="$(cat CHANGELOG.md)"
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          echo "$body" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.platform.binary_path }}
          asset_name: ${{ matrix.platform.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
          body: ${{ env.RELEASE_BODY }}

      - name: Upload SHA256 checksums
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.platform.asset_name }}.sha256
          asset_name: ${{ matrix.platform.asset_name }}.sha256
          tag: ${{ github.ref }}
          overwrite: true
